### PR TITLE
data cosmos mask 0.29 360

### PR DESCRIPTION
**Pull request by b-remy**
add mask from the full COSMOS catalog.
resolution: 0.29 arcmin/pixel
maps size: 360x360

### CODE REVIEW

**Comment by b-remy** [comment]
I added mocked COSMOS shear and convergence maps

**Comment by EiffL** [comment]
Thanks! just to make sure, can you list here what code you used to produce those?

**Comment by b-remy** [comment]
sure : https://github.com/CosmoStat/jax-lensing/blob/kappatng-dataset/notebooks/KappaTNG_COSMOS_emulation.ipynb

**Review by EiffL — APPROVED** [review]
Thanks!

**Comment by EiffL** [comment]
Great great great, with the notebooks linked in the PR, if something goes wrong later we can come back, see that the maps were added here, and remember how they were produced.

**Pull request merged**
