### PR TITLE
COSMOS WCS

### PR DESCRIPTION
**Pull request by b-remy**
Hi @EiffL ,

What do you think about this WCS header?

### CODE REVIEW

**Comment by EiffL** [comment]
hummm yeahhhh this looks legit, now the real test is if when you reread your file and the massey file, whether you can plot the maps on the same scale

**Comment by b-remy** [comment]
yep, I'm looking into it!

**Comment by b-remy** [comment]
With the last commit:
- the interpolation is done with `scipy.interpolate.interp2d` 
- and the WCS coordinates are now correct

see notebook [here](https://github.com/CosmoStat/jax-lensing/blob/cosmos_wcs/papers/Remy2021/COSMOSWCS.ipynb) .

cosmos_mass_maps

**Review by EiffL — APPROVED** [review]
LGTM

**Pull request merged**
